DONE - Fixed in CsvPath >> >> new run dialog do s and then down arrows — lots of new named-files are created letter by letter 		> same happens just for a regular add file?! DONE - added a date offsets panel and centralized now() in DateUtility within CsvPath Framework so we can set the apparent current date. DONE: >> stage data form still not staging new named-file DONE: Error creating examples: No such file or directory: '/Users/davidkershaw/dev/flightpath/flightpath/assets/examples/math/above_average.csvpaths' DONE:  File "/Users/davidkershaw/dev/flightpath/flightpath/widgets/content/content.py", line 69, in data_files_are_saved 		    if widget.editable == EditStates.UNEDITABLE NameError: name 'EditStates' is not defined DONE: synced up the initial README of paths and files DONE: >>> Loading a csvpath — shipping from examples/schemas: Cannot load named-paths group: 'NoneType' object has no attribute 'deleteLater' DONE: >> background caching worker is not working correctly and is eating space