FIXED: >>> error in save config configpanel: saving form: <flightpath.widgets.forms.config_form.ConfigForm(0x12ba53290) at 0x119b03fc0>   File "flightpath/widgets/forms/config_form.py", line 50, in add_to_config   File "flightpath/widgets/forms/config_form.py", line 84, in assure_env_path   File "csvpath/util/nos.py", line 167, in makedirs   File "csvpath/util/nos.py", line 232, in makedirs   File "<frozen os>", line 225, in makedirs FileExistsError: [Errno 17] File exists: '/users/davidkershaw/library/containers/com.flightpathdata.flightpath/data/flightpath/default/config' DONE: >>>> Error sending request (200): name 'os' is not defined DONE: >>> Lose the confirm message box on project create. It looks too much like an error and the projects list fills in immediately, which is enough. NOT DOING: >> config panel didn’t refresh after editing config.ini with an editor after close and reopen of the panel or project change. I had to stop and restart the app. DONE: >> config panel wasn’t updating correctly when switching projects because not correct reset MOSTLY DONE: > no way to delete a Mal-functioning project without going into the filesystem and editing .flightpath and the projects directory. Could we do a context menu in the project selector?  Alternatively a delete function in the config in the projects tab? <<< made more robust to incorrect paths in inputs and results. Still a lot of error dialogs and stop and restart app, but it is doable without going to the file system. It would be hell to do it, if you don’t know what you did — you’d need support. But support could at least walk you through it. For MVP that is good enough, imho. DONE >> Txt files — printouts.txt — that are generated by runs should be colored green when opened because not editable DONE > file info on an archive file doesn’t work DONE > inspector returns False if fewer data lines than sample lines DONE: > templates entered into the run dialog don’t get used. Templates set in a named-paths group definition file or at load-time do get used. DONE: >> change “listeners” to “integrations” in the config nav. Not in config.ini, just the ui. It will be more understandable that people look there for things like SFTP config. =====================================
DONE: Copy xlsx back from SFTP:
	local path does not exist. ready to do the copy from sftp://192.168.1.152:2022/inputs/named_files/energy/2023-reported-energy-and-water-metrics.xlsx/81e5ccfd6bcb36d0b694fa3d4447739b22abf8659888ce464dbccfb25ccba184.xlsx
	doing the copy to /Users/davidkershaw/FlightPath/test server 2/transfers/81e5ccfd6bcb36d0b694fa3d4447739b22abf8659888ce464dbccfb25ccba184(0).xlsx
Traceback (most recent call last):
  File "/Users/davidkershaw/dev/flightpath/flightpath/widgets/sidebars/sidebar_named_files.py", line 240, in _copy_file_back_to_cwd
    tto.write(ffrom.read())
  File "/Users/davidkershaw/Library/Caches/pypoetry/virtualenvs/flightpath-xvAT0a8o-py3.12/lib/python3.12/site-packages/csvpath/util/file_writers.py", line 145, in write
    file.write(data)
TypeError: write() argument must be str, not bytes
DONE: > copy back to working fails silently if the file is copied when a local file is selected with a NotADirectoryError. We should disambiguate. Or minimally, give an error message.
DONE: >>> config breaks on windows if \config\config.ini (absolute path).
DONE: >>> saved config doesn’t upload to the server. e.g. set logging to bare from full. Doesn’t take. <<<< possibly because of errors, not the change to config forms.
DONE: >>> config doesn’t refresh when you change projects. First project’s config stays with you. <<<< possibly because of errors