DONE: > AI jobs list doesn’t dark detect DONE:	 > fix the web hooks json — its hard to use and we can easily get it right DONE: > cannot load named-paths from json: 			  	File "flightpath/dialogs/load_paths_dialog.py", line 102, in __init__ 				AttributeError: 'NoneType' object has no attribute 'textChanged' DONE: > Json files in the json editor are not green even when uneditable DONE:	> in load named-paths dialog, enter a template, then type in the named-paths name text box — template field is cleared DONE: > reduced or eliminated segfaults due to right-hand trees and dialogs. DONE: 	>> toggle in context menu and data toolbar must be disabled when looking at an XLSX DONE:	> toggle in context menu must behave same as button in data toolbar when looking at an JSONL NOREPRO:	Crash errors on clicking on manifest.json in named-files: NOREPRO: >> the raw view toggle got stuck on disabled. Switching projects didn’t renewable it. Had to reopen app. first time you switch into CSVPATH file? But not every time. DONE: >	rt_tab_changed. not reacting.   		File "/Users/davidkershaw/dev/flightpath/flightpath/main.py", line 672, in _on_rt_tab_changed     		e = Path(doc.objectName()).suffix  		AttributeError: 'NoneType' object has no attribute 'objectName' DONE: >> no csvpath cmd line printouts from FlightPath — just capture to the one-off-run printer. Output doesn’t help and noticably slows down runs DONE: > save a json file from inputs/files back to project by right-clicking the tab works when a directory is selected, but fails silently when a file is selected DONE: > for csv files the save from inputs/files doesn’t do anything regardless. It should do a save-as NOREPRO: > Append csvpath to group doesn’t happen. no error message. Also watch for a crash around there. << if group.csvpaths is open you have to reopen to see changes