DONE: 	>> check file arrival setup form. I see “collect serially” rather than “collect_paths”. Could we be using the text from the drop down w/o translating it? DONE 	>> consistent crash on setting template in named-file or named-paths using the set template dialog: DONE:	>> set web hooks dialog does the same crash DONE: 	>> add “Setup AI” button to the splash. If no AI setup, splash always shows. If setup, only every 10 launches. DONE:	>> add “Find results” to the context menu on the named-paths directories. Just opens the find data dialog, same as we do in named-files DONE: 	>> updated the top left column image DONE:	>>> create new file using .txt with .txt not in data files extensions and get an unrecognized file type error. Txt and md should always be allowed. DONE: 	>> set web hooks dialog is modal — needs to be non-model so people can look at vars and help DONE: 	>> Error seen in first opening on MacOS with an old ~/flightpath dir:   File "flightpath/workers/precache_worker.py", line 41, in run DONE: 	>>	Unclearly when or why this happens. Added a try/except printout of view class and file. File "main.py", line 877, in update_views. AttributeError: 'JsonViewer2' object has no attribute 'on_edit_made' DONE:	>> csvpath editor — control keys (ctrl, shift, etc) still cause the file to be unsaved << seems to be only csvpath editor DONE: 	>> add save why am I seeing these results to pdf DONE:	>> cannot save file info report to pdf. Use save to pdf for one-off-runs DONE:	>> open jsonl as json, expand, and then beautify (should be the opposite of expand, really) doesn’t do anything. Fix: for jsonl don’t show beautify. Do something to make the file contract into well-formed jsonl. DONE:	>> check wellformedness of expanded jsonl gives an error. That is a bit confusing. It should either contract the data first or give an error message that explains that expanded jsonl is not valid jsonl, even if valid json. DONE:	>> raw view of jsonl should not be editable (I.e. raw coming from grid, not edit as json).  Disable the button. Fixing raw view for jsonl is out of scope for this release and anyway doesn’t add any value on top of edit-as-json. <<< made the button switch into json view DONE:  	>> fixed so tree clicks don’t automatically reread files without checking for existing tabs.